#!/bin/bash
#PBS -j oe
#PBS -m ae
#PBS -M momoe.yoshida@my.jcu.edu.au
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=1:mem=64gb
#PBS -o /home/heronlab/momoe/geo_polar_blended_sst/Linux_JCUHPC/blended_home/Logs/generate_oi_sst.log
#PBS -N generate_oi_sst

cd $PBS_O_WORKDIR

shopt -s expand_aliases
source /etc/profile.d/modules.sh
echo "Job identifier is $PBS_JOBID"
echo "Working directory is $PBS_O_WORKDIR"
 
module load matlab/2024a

matlab -nodisplay -nosplash -r "generate_oi_sst(2025,011); exit"
