#!/bin/bash
#PBS -j oe
#PBS -m ae
#PBS -M momoe.yoshida@my.jcu.edu.au
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=1:mem=64gb
#PBS -o /home/heronlab/momoe/geo_polar_blended_sst/Linux_JCUHPC/blended_home/Logs/generate_oi_input_data.log
#PBS -N generate_oi_input_data

cd $PBS_O_WORKDIR

# Add this to all of your scripts
shopt -s expand_aliases
source /etc/profile.d/modules.sh

# Output some useful information about
# the job we are running
echo "Job identifier is $PBS_JOBID"
echo "Working directory is $PBS_O_WORKDIR"

# Load the container we want to use
# It is a good idea to always specify the version number 
module load matlab/2024a


# -------------Note--------------------------------------
# stream options: 'msg' 
# run "python3 batch_geo_nav.py" in ../Python_code/

# Define date
year=2025
day=002
yesterday=$((day-1))

# Run your code
#matlab -nodisplay -nosplash -r "generate_oi_input_data(2025,011,'msg'); exit"
#matlab -nodisplay -nosplash -r "generate_oi_input_data(2025,011,'jpss'); exit"
#matlab -nodisplay -nosplash -r "generate_oi_input_data(2025,011,'goes'); exit"
#matlab -nodisplay -nosplash -r "generate_oi_input_data(2025,011,'all'); exit"
matlab -nodisplay -nosplash -r "try, init_files_OSTIA(${year},${yesterday}); init_all_biases(${year},${yesterday}); generate_oi_input_data(${year},${day},'all'); catch ME, disp(getReport(ME)); exit(1); end; exit"

